### ISSUE TITLE
windows_certificates does nothing within Kitchen

### ISSUE THREAD

**Issue by DanSibbernsen** [chef-cookbooks/windows#565]
### Cookbook versions
4.3.2, 3.1.0

### Chef-client version
14.2.0, 12.19.36

### Platform Details
Windows 10 (latest patches)
Windows Server 2016 (latest patches)
Created from Packer via [JacqInTheBox](https://github.com/jacqinthebox/packer-templates.git)
### Scenario:
I run Kitchen converge with the following recipe:
```
windows_certificate "#{node['Certificates']['location']}/certificate.pfx" do
  pfx_password '*****'
  store_name node['Certificates']['TrustedFolder']
  action :create
end
```

.kitchen.yml from my windows cookbook:
```
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: windows_10
    driver:
       box: windows_10
       provider: parallels
  - name: windows_server_2016
    driver:
       box: windows_server_2016
       provider: parallels
```

Notably: if I pass in the wrong password, the recipe fails to converge. But if the password is correct, the recipe appears to succeed but no certificate is pushed into the TRUSTEDFOLDER.

### Steps to Reproduce:
`kitchen create; kitchen converge;`

The issue started sometime between Summer of 2017 and Spring of 2018. I've got several working cases on outside environments, but Kitchen can't install my certificates or the certificates located in the [Windows cookbook source](https://github.com/chef-cookbooks/windows). Nothing appears in the mmc.exe when I load up the Certificates snap-in (this is true for both "My user account" and "Computer account").

The next level of debugging would be into the ruby gem of win32-certstore, but I'm not sure how I would go about doing that via Kitchen.

### Expected Result:
I expect the certificate to be installed and configured correctly.

### Actual Result:
No certificate is created.
